### ISSUE TITLE
PagesHome.html

### ISSUE THREAD

**Issue by selim** [tedarek/tedarek-ui#6]
https://minisoft.com.tr/tedarek/demo/demo3/tedarekV2_robotoSlab/pagesHome.html

[ ] Fontlar eski kalmış
[ ] Arama motoru altındaki kategori listesi kaydırmalı olarak konulabilir tümünü gör e gerek kalmamalı. 

- [x] Bu kısım ana sayfadan çıkarılacak. ( İlerleyen zamanda eklenecek)

![image](https://user-images.githubusercontent.com/78073035/109266182-bff53b00-7818-11eb-9ac1-bd0aefa02d99.png)

- [x] Genel olarak tüm sayfalardaki metin ve görseller olması gerekenden fazla büyük. Mac lerde normal gözükebilir ancak windows da büyük görünüyor
![image](https://user-images.githubusercontent.com/78073035/109266327-f763e780-7818-11eb-91fc-8afcb59fdeed.png)

- [x] Kategoriler ve şehirler girilecek. Veri deseni ve bilgilendirme referans alınmalı
![image](https://user-images.githubusercontent.com/78073035/109266587-50cc1680-7819-11eb-996a-cd3da097b549.png)

- [x] Etiketlerde tümünü gör olmalı.
![image](https://user-images.githubusercontent.com/78073035/109267187-37779a00-781a-11eb-94bc-7afc5fe739fa.png)

**Comment by velihankara** [comment]
Genel olarak tüm sayfalardaki metin ve görseller olması gerekenden fazla büyük. Mac lerde normal gözükebilir ancak windows da büyük görünüyor
=> Toplantıda konuşuldu ve bir değişiklik yapıulmayacağına karar verildi

**Comment by velihankara** [comment]
=>  Kategoriler ve şehirler girilecek. Veri deseni ve bilgilendirme referans alınmalı
Panel bağlantısı gerçekleştiğinde tümü eklenmiş olacak

**Comment by velihankara** [comment]
[ ] Arama motoru altındaki kategori listesi kaydırmalı olarak konulabilir tümünü gör e gerek kalmamalı.

=> düzenlendi örnek olarak var olan kategoriler tekrarlandı panel bağlantısı yapıldığında hepsi farklı olucak

**Comment by velihankara** [comment]
https://minisoft.com.tr/tedarek/demo/demo4/pagesHome.html

**Comment by selim** [comment]
> [ ] Arama motoru altındaki kategori listesi kaydırmalı olarak konulabilir tümünü gör e gerek kalmamalı.
> 
> 
> 
> => düzenlendi örnek olarak var olan kategoriler tekrarlandı panel bağlantısı yapıldığında hepsi farklı olucak

@enesboyaci @emreisti @eemreozdemir 
deneme cevabıdır dikkate almayın

**Comment by velihankara** [comment]
> > [ ] Arama motoru altındaki kategori listesi kaydırmalı olarak konulabilir tümünü gör e gerek kalmamalı.
> > => düzenlendi örnek olarak var olan kategoriler tekrarlandı panel bağlantısı yapıldığında hepsi farklı olucak
> 
> @enesboyaci @emreisti @eemreozdemir
> deneme cevabıdır dikkate almayın
