### ISSUE TITLE
https://minisoft.com.tr/tedarek/demo/demo3/tedarekV2_robotoSlab/pagesCompanyProfile.html

### ISSUE THREAD

**Issue by emreisti** [tedarek/tedarek-ui#7]
https://minisoft.com.tr/tedarek/demo/demo3/tedarekV2_robotoSlab/pagesCompanyProfile.html

- [x] Outdoor planlama , Medya planlama (Resimler ) ve altında bulunan teklif al kaldırılmalı

![image](https://user-images.githubusercontent.com/78073035/109267870-4f035280-781b-11eb-8185-37d1646b958b.png)

**Comment by velihankara** [comment]
https://minisoft.com.tr/tedarek/demo/demo4/pagesCompanyProfile.html
