### ISSUE TITLE
https://minisoft.com.tr/tedarek/demo/demo3/tedarekV2_robotoSlab/pagesUserProfile.html

### ISSUE THREAD

**Issue by emreisti** [tedarek/tedarek-ui#8]
https://minisoft.com.tr/tedarek/demo/demo3/tedarekV2_robotoSlab/pagesUserProfile.html

- [x] Kare içerisine aldıklarımız çıkartılmalı 

![image](https://user-images.githubusercontent.com/78073035/109272875-83c6d800-7822-11eb-8849-447cf8e9e715.png)

- [x] Bu bölüm komple kaldırılacaktır
![image](https://user-images.githubusercontent.com/78073035/109272760-61cd5580-7822-11eb-8f89-e89a48b3dc71.png)

- [x] Profil sayfasınındaki resimi kaldıralım sizler daha yakısıklısınız :) kendi fotonuzu koyabilirsiniz. 
- [x] Yukarıda 3 tane alarım butonu görünüyor o bölümü yeniden tasarlayalım

![image](https://user-images.githubusercontent.com/78073035/109273056-ba9cee00-7822-11eb-956a-355930353652.png)

**Comment by velihankara** [comment]
Yukarıda 3 tane alarım butonu görünüyor o bölümü yeniden tasarlayalım
=> Opsiyonel olarak tasarlanmıştır. Yazılımda 1 adet görünecek

**Comment by velihankara** [comment]
https://minisoft.com.tr/tedarek/demo/demo4/pagesUserProfile.html
